name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true

  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: [Build]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
      - name: Ensure unit test script is executable
        run: chmod +x ci/unit-test-app.sh
      - name: Run unit tests
        run: ci/unit-test-app.sh

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          
